name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:
    permissions:
      users:
        - SwarnimWalavalkar

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"
          scope: "@swarnim"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
